[general]
mucs_instance_code = "mm5000"

[paths]
sqlite3_path = "/cluster/pixstor/class/mm5000/data/"

[canvas]
# The Canvas LMS Token identifying your user session.
canvas_token = "16765~PnzNMauTnTJEDCh7DUFzmFULcPeQDayFcHtnXM9u2CKBWan38HDAGMBHVeVXAWQE"
# The Canvas LMS course ID identifying your course.
canvas_course_id = 306521
# The naming scheme of your assignments as found on your course.
# The script will attempt to find as many assignments that have this predicate.
canvas_assignment_name_predicate = "Lab "
# List any words that can be in assignments that you do not want included in the search.
canvas_assignment_phrase_blacklist = [""]
